# Generated by Django 3.0.6 on 2020-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='birth_date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
    ]
