# Generated by Django 3.0.6 on 2020-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200510_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscription',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
