# Generated by Django 3.0.6 on 2020-05-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emial_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscription',
            field=models.IntegerField(default=0),
        ),
    ]
