# Generated by Django 3.0.6 on 2020-06-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200604_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=0, verbose_name='body'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
