# Generated by Django 3.0.6 on 2020-06-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200608_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='picture'),
        ),
    ]
